STR_OUTPUT_SLICE = 20

MAX_LENGTH_USERNAME = 150
MAX_FIRST_NAME_CHAR_LENGTH = 150
MAX_LAST_NAME_CHAR_LENGTH = 150

MAX_CHAR_LENGTH = 256

MAX_TAG_NAME_CHAR_LENGTH = 32
MAX_TAG_SLUG_CHAR_LENGTH = 32

MAX_INGREDIENT_NAME_CHAR_LENGTH = 128
MAX_INGREDIENT_MEASUREMENT_UNIT_CHAR_LENGTH = 64
MIN_INGREDIENT_AMOUNT_QUANTITY = 1

MAX_LENGTH_SHORT_LINK = 255

MIN_COOKING_TIME = 1

MIN_HASHIDS_LENGTH = 3
