# Generated by Django 3.2.3 on 2024-12-27 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241222_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourite_recipes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
    ]
